version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  hello-world:
    jobs:
      - build
  

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\HelloWorld
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Yes"
          command: sleep 42300
      